[supervisord]
nodaemon=true
user=www-data
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[inet_http_server]
port=127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001

[program:war-room-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --sleep=3 --tries=3 --timeout=660 --queue=war-room
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=3
redirect_stderr=true
stdout_logfile=/var/log/supervisor/war-room-worker.log
stopwaitsecs=3600

[program:general-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --sleep=3 --tries=3 --timeout=660 --queue=default,document-conversion,api-audit
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/general-worker.log
stopwaitsecs=3600

[program:auto-scaler]
command=php /var/www/html/artisan workers:auto-scale
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/auto-scaler.log
